Feat: Transformative flavour
grammyjs/emoji pull request #9
Opened 2022-03-24 19:55 UTC by andrrms

Changes made, needs review.
If merged, plugin version will go to 2.0.0, as it also changes the name of the flavoring interface.
Fix #8

2022-03-26 11:59 UTC, KnorpelSenf requested changes

2022-03-26 11:59 UTC, KnorpelSenf commented on src/mod.ts
> +export type EmojiFlavour<C extends Context> = Flavour & C;
This is BrE, please use AmE (`Flavor` rather than `Flavour`)

2022-03-26 12:02 UTC, KnorpelSenf commented
This does not fix #8. This PR would need to extract the return type of `ctx.reply` and use it in `ctx.replyWithEmoji`.

2022-03-28 16:16 UTC, andrrms commented
Major version change will not be required anymore.

2022-03-28 22:20 UTC, KnorpelSenf commented
Note that you're admin in the repo, there's no need to open pull requests from the fork. You can just open them from other branches in the same repo :)

2022-03-28 22:48 UTC, KnorpelSenf reviewed
This still does not solve the issue.

The aim is to make the following code compile:

```ts
import { Bot } from "https://deno.land/x/grammy/mod.ts";
import {
    hydrate,
    HydrateFlavor,
} from "https://deno.land/x/grammy_hydrate/mod.ts";

type MyContext = EmojiFlavor<HydrateFlavor<Context>>;

const bot = new Bot<MyContext>("");

bot.use(hydrate(), emojiParser(), async (ctx) => {
    const first = await ctx.reply("Ehh");
    await first.delete();
    const res = await ctx.replyWithEmoji`Hi! ${"robot"}`;
    await res.delete();
});
```
However, I cannot get it to work myself. It seems like `ReturnType` somehow swallows the changes that the inner transformative context flavour is performing to `ctx.reply`. Hence, the emoji flavour does not pick this up so it cannot provide the same type signature as `ctx.reply` has.

I do not see how this can be fixed. Feel free to investigate. Perhaps the hydrate plugin needs to be adjusted, too, who knows.

2022-03-30 16:32 UTC, KnightNiwrem commented
> This still does not solve the issue.
> 
> The aim is to make the following code compile:
> 
> ```ts
> import { Bot } from "https://deno.land/x/grammy/mod.ts";
> import {
>     hydrate,
>     HydrateFlavor,
> } from "https://deno.land/x/grammy_hydrate/mod.ts";
> 
> type MyContext = EmojiFlavor<HydrateFlavor<Context>>;
> 
> const bot = new Bot<MyContext>("");
> 
> bot.use(hydrate(), emojiParser(), async (ctx) => {
>     const first = await ctx.reply("Ehh");
>     await first.delete();
>     const second = await ctx.replyWithEmoji`Hi! ${"robot"}`;
>     await second.delete();
> });
> ```
> 
> However, I cannot get it to work myself. It seems like `ReturnType` somehow swallows the changes that the inner transformative context flavour is performing to `ctx.reply`. Hence, the emoji flavour does not pick this up so it cannot provide the same type signature as `ctx.reply` has.
> 
> I do not see how this can be fixed. Feel free to investigate. Perhaps the hydrate plugin needs to be adjusted, too, who knows.

It doesn't appear to be _just_ `ReturnType`, but rather a behavior of Typescript, itself. It seems like function type intersections are essentially treated as overloads, and Typescript will simply pick one of them for the return value type (without much consistency).

[Typescript Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgIQjANHGBPMBTOAYQgDsY8APeAXzgDMoIQ4ByAcygEMQRsWBuAFCCc+OAFk4AXiKlyVANoAiKHjAAbbAHVgMABYBBAK4ATYBCUBdOADJZZSjGWqN2K7fvynKtZp36DElBOGHMSKyFRAgAlaThovBgjKBIAFVw8AB5xAD4hQRM8AGN1TlU4ItIAZ3gYAC4JIUqSGrgoOJgACiUlAEohIA)

2022-03-30 20:32 UTC, andrrms commented
> Note that you're admin in the repo, there's no need to open pull requests from the fork. You can just open them from other branches in the same repo :)

I do it on impulse, I'm still learning to use git 😅

2022-03-31 12:34 UTC, KnorpelSenf commented
> It seems like function type intersections are essentially treated as overloads

This is correct, it makes a lot of sense that this is the root cause of the issue.

I'm still unsure how to proceed from here.

2022-04-01 15:39 UTC, KnightNiwrem commented
@andrrms @KnorpelSenf Please take a look at https://github.com/grammyjs/hydrate/pull/1/files if it may be a potential workaround.

2022-04-11 13:54 UTC, KnorpelSenf commented
@andrrms can you please check out https://github.com/grammyjs/hydrate/pull/1 and confirm that everything works for you?

2022-04-13 12:26 UTC, closed without merging